### ISSUE TITLE
About article: A Fast Geometric Regularizer to Mitigate Event Collapse in the Contrast Maximization Framework

### ISSUE THREAD

**Issue by huangfeng95** [tub-rip/event_collapse#1]
Do you plan to open source relevant code for reference?

**Comment by shiba24** [comment]
Hi @huangfeng95 , thank you for the interest.
I have not thought about it, but yes definitely I can. I'm a bit busy now, so please give me some time to prepare.

**Comment by huangfeng95** [comment]
@shiba24 Thank you for your reply and wish everything goes well with your work!
